- type: job
  id: M14HeadOfVDNH
  name: job-name-head-of-vdnh
  description: job-description-head-of-vdnh
  playTimeTracker: M14HeadOfVDNH
  startingGear: M14HeadOfVDNHGear
  icon: "JobIconVDNH"
  canBeAntag: true

- type: startingGear
  id: M14HeadOfVDNHGear
  equipment:
    head: M14ClothingHeadHatUshankaBlack
    neck: M14ClothingNeckMantleVDNH
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: M14ClothingShoesValenki
    gloves: ClothingHandsGlovesHop
    back: ClothingBackpackMerc
    pocket1: SurvivalKnife
    pocket2: M14HeadOfVDNKHKey
  inhand:
    - M14CasingLighter
  storage:
    back:
    - M14RadioHandheldVDNH
    - M14WeaponShotgunAshot
    - ShellShotgunSlug
