- type: job
  id: M14SecurityVDNH
  name: job-name-security-vdnh
  description: job-description-security-vdnh
  playTimeTracker: M14SecurityVDNH
  startingGear: M14SecurityVDNHGear
  icon: "JobIconVDNH"
  canBeAntag: true
 
- type: startingGear
  id: M14SecurityVDNHGear
  equipment:
    head: ClothingHeadHelmetScrap
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsWork
    back: ClothingBackpack
    pocket1: SurvivalKnife
    pocket2: M14WeaponShotgunAshot
  inhand:
    - M14CasingLighter
  storage:
    back:
    - M14RadioHandheldVDNH
    - M14VDNKHKey
    - ShellShotgunSlug

