- type: job
  id: M14StalkerVDNH
  name: job-name-stalker-vdnh
  description: job-description-stalker-vdnh
  playTimeTracker: M14StalkerVDNH
  startingGear: M14StalkerVDNHGear
  icon: "JobIconVDNH"
  canBeAntag: true

- type: startingGear
  id: M14StalkerVDNHGear
  equipment:
    head: M14ClothingHeadHatUshankaBrown
    jumpsuit: M14ClothingUniformTelogreykaBrown
    id: M14Tablet
    shoes: M14ClothingShoesValenki
    gloves: ClothingHandsGlovesHop
    back: ClothingBackpack
    pocket1: M14WeaponShotgunAshot
    pocket2: M14RadioHandheldVDNH
  storage:
    back:
    - ShellShotgunSlug
  inhand:
    - M14CasingLighter
    
