- type: job
  id: M14HeadOfSparta
  name: Полковник Спарты
  description: Вы лидер спарты. Храните клятву,защищайте метро
  playTimeTracker: M14HeadOfSparta
  startingGear: M14HeadOfSpartaGear
  icon: "JobIconSparta"
  canBeAntag: false
  whitelisted: true

- type: startingGear
  id: M14HeadOfSpartaGear
  equipment:
    head: ClothingHeadHatBeretHoS
    neck: M14ClothingNeckCloakSparta
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformJumpsuitSparta
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsMercGlovesCombat
    back: ClothingMilitaryBackpack
    pocket2: M14HeadOfSpartaKey
