- type: job
  id: M14MedicSparta
  name: Медик спарты
  description: Вы медик спарты. Помогайте своим товарищам и окружающим.
  playTimeTracker: M14MedicSparta
  startingGear: M14MedicSpartaGear
  supervisors: job-supervisors-sparta
  icon: "JobIconSparta"
  canBeAntag: true
  
- type: startingGear
  id: M14MedicSpartaGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    mask: ClothingMaskBreathMedicalSecurity
    jumpsuit: M14ClothingUniformJumpsuitSparta
    id: M14Tablet
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesLatex
    back: ClothingMilitaryBackpack
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - M14RadioHandheldSparta
    - M14SpartaKey
