- type: job
  id: M14MedicSparta
  name: Медик спарты
  description: Вы медик спарты. Помогайте своим товарищам и окружающим.
  playTimeTracker: M14MedicSparta
  startingGear: M14MedicSpartaGear
  icon: "JobIconSparta"
  canBeAntag: true
  access:
    - M14Sparta

- type: startingGear
  id: M14MedicSpartaGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    mask: ClothingMaskBreathMedicalSecurity
    jumpsuit: ClothingUniformJumpsuitOperative
    id: M14Tablet
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesLatex
    back: ClothingMilitaryBackpack
    belt: ClothingBeltMilitaryWebbingMedFilled