- type: job
  id: M14SoldierSparta
  name: Солдат спарты
  description: Храните клятву,защищайте метро
  playTimeTracker: M14SoldierSparta
  startingGear: M14SoldierSpartaGear
  icon: "JobIconSparta"
  supervisors: job-supervisors-sparta
  canBeAntag: true

- type: startingGear
  id: M14SoldierSpartaGear
  equipment:
    jumpsuit: M14ClothingUniformJumpsuitSparta
    mask: ClothingMaskNeckGaiter
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingMilitaryBackpack
  storage:
    back:
    - M14RadioHandheldSparta
    - M14SpartaKey
