- type: job
  id: M14PolitHandRedLine
  name: Политрук
  description: Вы обязаны подчиняться генсеку,нести идеологию коммунизма в массы и проводить идеологическую работу с составом станции
  playTimeTracker: M14PolitHandRedLine
  startingGear: M14PolitHandRedLineGear
  icon: "JobIconRedline"
  canBeAntag: true
  accessGroups:
    - M14RedLine

- type: startingGear
  id: M14PolitHandRedLineGear
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
  inhand:
    - BriefcaseBrownFilled