- type: job
  id: M14PolitHandRedLine
  name: Политрук
  description: Вы обязаны подчиняться генсеку,нести идеологию коммунизма в массы и проводить идеологическую работу с составом станции
  playTimeTracker: M14PolitHandRedLine
  startingGear: M14PolitHandRedLineGear
  icon: "JobIconRedline"
  supervisors: job-supervisors-politruk
  canBeAntag: true

- type: startingGear
  id: M14PolitHandRedLineGear
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformJumpsuitRedLine
    id: M14Tablet
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
  inhand:
    - BriefcaseBrownFilled
