- type: job
  id: M14SoldierRedline
  name: Солдат Красной Линии
  description: Вы обязаны подчиняться генсеку и политруку и нести идеологию коммунизма.
  playTimeTracker: M14SoldierRedLine
  startingGear: M14SoldierRedLineGear
  icon: "JobIconRedline"
  canBeAntag: true
  access:
    - M14RedLine

- type: startingGear
  id: M14SoldierRedLineGear
  equipment:
    mask: ClothingMaskNeckGaiterRed
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpack