- type: job
  id: M14TechnicTech
  name: Техник
  description: Закупайте ресурсы у сталкеров,собирайте самое ценное на своих станках
  playTimeTracker: M14TechnicTech
  startingGear: M14TechnicTechGear
  supervisors: job-supervisors-tech
  icon: "JobIconTech"
  canBeAntag: true

- type: startingGear
  id: M14TechnicTechGear
  equipment:
    jumpsuit: M14ClothingUniformTelogreykaBrown
    id: M14Tablet
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesColorLightBrown
    back: ClothingBackpack
    belt: ClothingBeltUtilityEngineering
    pocket1: M14WeaponShotgunAshot
  storage:
    back:
    - M14RadioHandheldTehnick
    - M14KTechKey
