- type: job
  id: M14HeadOfHansa
  name: Начальник станции
  description: Вы главный в ганзе
  playTimeTracker: M14HeadOfHansa
  startingGear: M14HeadOfHansaGear
  icon: "JobIconHansa"
  canBeAntag: false
  accessGroups:
    - M14Hansa

- type: startingGear
  id: M14HeadOfHansaGear
  equipment:
    head: ClothingHeadHatBeretFrench
    neck: M14ClothingNeckMantleHansa
    jumpsuit: ClothingUniformJumpsuitTacticool
    id: M14Tablet
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsMercGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    back: ClothingMilitaryBackpack
    pocket1: M14HeadOfHansaKey
    pocket2: M14HansaPassport