- type: job
  id: M14HeadOfHansa
  name: Начальник станции
  description: Вы главный в ганзе
  playTimeTracker: M14HeadOfHansa
  startingGear: M14HeadOfHansaGear
  icon: "JobIconHansa"
  canBeAntag: false

- type: startingGear
  id: M14HeadOfHansaGear
  equipment:
    head: ClothingHeadHatBeretFrench
    neck: M14ClothingNeckMantleHansa
    jumpsuit: M14ClothingUniformJumpsuitHeadofHansa
    id: M14Tablet
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsMercGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    back: ClothingMilitaryBackpack
    pocket1: M14HeadOfHansaKey
  storage:
    back:
    - M14HansaPassport
    - M14RadioHandheldGanza
