- type: job
  id: M14OfficerHansa
  name: Офицер Ганзы
  description: Вы обязаны следить за всеми,кто идет через границу станции
  playTimeTracker: M14OfficerHansa
  startingGear: M14OfficerHansaGear
  supervisors: job-supervisors-ganza
  icon: "JobIconHansa"
  canBeAntag: true

- type: startingGear
  id: M14OfficerHansaGear
  equipment:
    head: ClothingHeadHatBeretMerc
    jumpsuit: M14ClothingUniformJumpsuitOfficer
    id: M14Tablet
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsCombatFilled
    back: ClothingBackpackMerc
    pocket2: M14HansaKey
  storage:
    back:
    - M14HansaPassport
    - M14RadioHandheldGanza
    
