- type: job
  id: M14OfficerHansa
  name: Офицер Ганзы
  description: Вы обязаны следить за всеми,кто идет через границу станции 
  playTimeTracker: M14OfficerHansa
  startingGear: M14OfficerHansaGear
  icon: "JobIconHansa"
  canBeAntag: true
  access:
    - M14Hansa

- type: startingGear
  id: M14OfficerHansaGear
  equipment:
    head: ClothingHeadHatBeretMerc
    jumpsuit: ClothingUniformJumpsuitTacticool
    id: M14Tablet
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsCombatFilled
    back: ClothingBackpackMerc
    pocket1: M14HansaPassport