- type: job
  id: M14TradeAgentHansa
  name: Торговый агент ганзы
  description: Вы обязаны следить за всем что идет через границу станции
  playTimeTracker: M14TradeAgentHansa
  startingGear: M14TradeAgentHansaGear
  supervisors: job-supervisors-torg
  icon: "JobIconHansa"
  canBeAntag: true

- type: startingGear
  id: M14TradeAgentHansaGear
  equipment:
    head: ClothingHeadHatBowlerHat
    jumpsuit: M14ClothingUniformJumpsuitHansaTradeAgent
    id: M14Tablet
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
    pocket2: M14HansaPassport
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampTrader
