- type: job
  id: M14HeadOfHydra
  name: Фюрер
  description: Вы великий вождь.
  playTimeTracker: M14HeadOfHydra
  startingGear: M14HeadOfHydraGear
  icon: "JobIconHydra"
  canBeAntag: false
  whitelisted: true
  accessGroups:
    - M14Hydra

- type: startingGear
  id: M14HeadOfHydraGear
  equipment:
    head: M14ClothingHeadHatBeaverHat
    neck: M14ClothingNeckCloakHydra
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingMilitaryBackpack
    pocket1: M14HeadOfHydraKey