- type: job
  id: M14Minister
  name: Председатель Гидры
  description: Вы второй человек после фюрера. Вы не имеете права идти против воли вождя,вы должны руководить солдатами и следить за деятельностью внутри станции.
  playTimeTracker: M14MinisterHydra
  startingGear: M14MinisterHydraGear
  icon: "JobIconHydra"
  supervisors: job-supervisors-predsedatel
  canBeAntag: true

- type: startingGear
  id: M14MinisterHydraGear
  equipment:
    head: ClothingHeadHatBeretSecurityPilot
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformJumpsuitHydra
    id: M14Tablet
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackSatchel
    pocket1: LuxuryPen
  inhand:
    - BriefcaseBrownFilled
