- type: job
  id: M14SoldierHydra
  name: Солдат Гидры
  description: Вы великий представитель гидры. Цвет метро.
  playTimeTracker: M14SoldierHydra
  startingGear: M14SoldierHydraGear
  supervisors: job-supervisors-gydra
  icon: "JobIconHydra"
  canBeAntag: true

- type: startingGear
  id: M14SoldierHydraGear
  equipment:
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformJumpsuitHydra
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpack
  storage:
    back:
    - M14RadioHandheldGidra
    - M14HydraKey
