- type: job
  id: M14SoldierHydra
  name: Солдат Гидры
  description: Вы великий представитель гидры. Цвет метро.
  playTimeTracker: M14SoldierHydra
  startingGear: M14SoldierHydraGear
  icon: "JobIconHydra"
  canBeAntag: true
  access:
    - M14Hydra

- type: startingGear
  id: M14SoldierHydraGear
  equipment:
    mask: ClothingMaskNeckGaiter
    jumpsuit: M14ClothingUniformTelogreykaBlack
    id: M14Tablet
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpack